apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    {{- template "labels" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels" . | indent 2 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | indent 4 }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
