apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-role-binding
subjects:
  - kind: User
    name: Alice
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-role-binding
subjects:
  {{- range .Values.users }}
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
  {{- end }}
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io


{{- range .Values.users }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-role-binding
subjects:
  - kind: User
    name: {{ .name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
