apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.deployment.name }}
  type: NodePort
